<?php require 'templates/layout/header.phtml' ?>

<div class="main-container">

    <?php if ($error): ?>
        <div class='alert alert-danger' role='alert'>
            <?= $error ?>
        </div>
    <?php endif ?>

    <div class="d-flex flex-column align-items-center">
        <img class="action-icon" src="assets/icons/login.png" alt="login"/>
        <form method="post" action="login" class="form">
            <div class="form-group">
                <label for="username">Usuario</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary my-2">Ingresar</button>
            </div>
        </form>
    </div>
</div>

<?php require 'templates/layout/footer.phtml' ?>
