<?php require 'templates/layout/header.phtml' ?>

<div class="main-container">
    <p class="text-center fs-1 my-4">Listado de viajes</p>
    <ul class="list-group">
    <?php foreach($trips as $trip): ?>
        <li class="list-group-item d-flex justify-content-between gap-5 align-items-center">
            <div class="countries-container flex-column">
                <div class="my-2">
                    <img src="assets/icons/plane-departure.png" class="icon" alt="plane-departure"/>
                    <b><?= htmlspecialchars($trip->pais) ?></b> | <?= htmlspecialchars($trip->ciudad) ?>
                </div>
                <div class="my-2">
                    <img src="assets/icons/plane-arrival.png" class="icon" alt="plane-arrival"/>
                    <b><?= htmlspecialchars($trip->pais_destino) ?></b> | <?= htmlspecialchars($trip->ciudad_destino) ?>
                </div>                
            </div>
            <div class="date-container flex-column">
                <div class="my-2">
                    <img src="assets/icons/date.png" class="icon" alt="start date"/>
                    <b>Ida: </b>
                    <?php if($trip->fecha_ini != '0000-00-00'): ?> 
                        <?= htmlspecialchars($trip->fecha_ini) ?>
                    <?php else: ?>
                        Sin información  
                    <?php endif ?>
                </div>
                <div class="my-2">
                    <img src="assets/icons/date.png" class="icon" alt="end date"/>
                    <b>Vuelta: </b>
                    <?php if($trip->fecha_fin != '0000-00-00'): ?> 
                        <?= htmlspecialchars($trip->fecha_fin) ?>
                    <?php else: ?>
                        Sin información 
                    <?php endif ?>
                </div>
            </div>
            <div class="passenger-container text-capitalize">
                <span class="d-flex flex-row">
                    <img class="d-flex justify-content-center icon" src="assets/icons/user.png" alt="user"/>
                    <b>Pasajero: &nbsp;</b><?= htmlspecialchars($trip->nombre) ?>, <?= htmlspecialchars($trip->apellido) ?>
                </span>
            </div>
            <div>
                <?php $viewDetailUrl = BASE_URL . 'viaje/' . $trip->viaje_id; ?>
                <button class="btn btn-primary" onclick="location.href='<?php echo $viewDetailUrl; ?>'" type="button">Ver detalle</button>
            </div>
        </li>
    <?php endforeach ?>
    </ul>
</div>

<?php require 'templates/layout/footer.phtml' ?>