<?php require 'templates/layout/header.phtml' ?>

<div class="main-container">
    <p class="text-center fs-1 my-4">Detalle del viaje</p>

    <div class="card text-center">
        <div class="card-header d-flex justify-content-evenly">
            <div class="detail-item">
                <img src="assets/icons/plane-departure.png" class="icon" alt="plane-departure"/>
                <b><?= htmlspecialchars($trip->pais) ?></b> | <?= htmlspecialchars($trip->ciudad) ?>
            </div>
            <div class="detail-item">
                <img src="assets/icons/plane-arrival.png" class="icon" alt="plane-arrival"/>
                <b><?= htmlspecialchars($trip->pais_destino) ?></b> | <?= htmlspecialchars($trip->ciudad_destino) ?>
            </div>
        </div>
        <div class="card-body d-flex justify-content-evenly">
            <div class="card-text full-width d-flex justify-content-evenly">
                <div class="detail-item">
                    <img src="assets/icons/date.png" class="icon" alt="start date"/>
                    <b>Ida: </b>
                    <?php if($trip->fecha_ini != '0000-00-00'): ?> 
                        <?= htmlspecialchars($trip->fecha_ini) ?>
                    <?php else: ?>
                        Sin información  
                    <?php endif ?>
                </div>
                <div class="detail-item">
                    <img src="assets/icons/date.png" class="icon" alt="end date"/>
                    <b>Vuelta: </b>
                    <?php if($trip->fecha_fin != '0000-00-00'): ?> 
                        <?= htmlspecialchars($trip->fecha_fin) ?>
                    <?php else: ?>
                        Sin información 
                    <?php endif ?>
                </div>
            </div>
        </div>
        <div class="text-capitalize card-footer d-flex flex-column align-items-center">
            <span class="d-flex flex-row">
                <img class="d-flex justify-content-center icon" src="assets/icons/user.png" alt="user"/>
                <b>Pasajero: &nbsp;</b><?= htmlspecialchars($trip->nombre) ?>, <?= htmlspecialchars($trip->apellido) ?>
            </span>
            <span class="d-flex justify-content-center">
                <img src="assets/icons/email.png" class="icon" alt="email"/>
                <b>Contacto: &nbsp;</b><span class="text-lowercase"><?= htmlspecialchars($trip->correo) ?></span>
            </span>
        </div>
    </div>
</div>

<?php require 'templates/layout/footer.phtml' ?>