<?php require 'templates/layout/header.phtml' ?>

<div class="main-container">
    <p class="text-center fs-1 my-4">Listado de viajes</p>
    <ul class="list-group">
    <?php foreach($trips as $trip): ?>
        <li class="list-group-item d-flex justify-content-between gap-5 align-items-center">
            <div class="countries-container flex-column">
                <div class="my-2">
                    <img src="assets/icons/plane-departure.png" class="icon" alt="plane-departure"/>
                    <b><?= htmlspecialchars($trip->pais) ?></b> | <?= htmlspecialchars($trip->ciudad) ?>
                </div>
                <div class="my-2">
                    <img src="assets/icons/plane-arrival.png" class="icon" alt="plane-arrival"/>
                    <b><?= htmlspecialchars($trip->pais_destino) ?></b> | <?= htmlspecialchars($trip->ciudad_destino) ?>
                </div>                
            </div>
            <div class="date-container flex-column">
                <div class="my-2">
                    <img src="assets/icons/date.png" class="icon" alt="start date"/>
                    <b>Ida: </b>
                    <?php if($trip->fecha_ini != '0000-00-00'): ?> 
                        <?= htmlspecialchars($trip->fecha_ini) ?>
                    <?php else: ?>
                        Sin información  
                    <?php endif ?>
                </div>
                <div class="my-2">
                    <img src="assets/icons/date.png" class="icon" alt="end date"/>
                    <b>Vuelta: </b>
                    <?php if($trip->fecha_fin != '0000-00-00'): ?> 
                        <?= htmlspecialchars($trip->fecha_fin) ?>
                    <?php else: ?>
                        Sin información 
                    <?php endif ?>
                </div>
            </div>
            <div class="passenger-container text-capitalize">
                <span class="d-flex flex-row">
                    <img class="d-flex justify-content-center icon" src="assets/icons/user.png" alt="user"/>
                    <b>Pasajero: &nbsp;</b><?= htmlspecialchars($trip->nombre) ?>, <?= htmlspecialchars($trip->apellido) ?>
                </span>
            </div>
            <div class="d-flex gap-1 align-items-center">
                <?php $viewDetailUrl = BASE_URL . 'viaje/' . $trip->viaje_id; ?>
                <button class="btn btn-primary" onclick="location.href='<?php echo $viewDetailUrl; ?>'" type="button">Ver detalle</button>
                <?php if($res->user): ?>
                    <button class="btn btn-danger" onclick="openPopup(<?= $trip->viaje_id ?>)" type="button">
                        <img class="d-flex justify-content-center icon" src="assets/icons/delete.png" alt="delete"/>
                    </button>
                <?php endif ?>
            </div>
        </li>
    <?php endforeach ?>
    </ul>
</div>

<div class="popup-overlay" id="popup">
    <div class="popup-content">
        <h4 class="mb-3">Está seguro que desea eliminar este viaje?</h4>
        <div class="d-flex flex-row gap-5 justify-content-evenly">
            <button class="btn btn-primary" onclick="closePopup()" type="button">No, volver</button>
            <button class="btn btn-danger" id="confirmDeleteBtn" type="button">Si, eliminar</button>
        </div>
    </div>
</div>

<?php require 'templates/layout/footer.phtml' ?>

<script>
    function openPopup(tripId) {
        const deleteUrl = `<?php echo BASE_URL; ?>borrarViaje/${tripId}`;
        document.getElementById('confirmDeleteBtn').setAttribute('onclick', `closePopup(); location.href='${deleteUrl}'`);
        document.getElementById('popup').style.display = 'flex';
    }

    function closePopup() {
        document.getElementById('popup').style.display = 'none';
    }
</script>