<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
    <title>Viajes</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href=""><img src="assets/icons/logo.png" class="logo" alt="logo"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="">Viajes</a>
                        </li>
                        <?php if (!$this->user): ?>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="mostrarLogin">Ingresar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="mostrarRegistro">Registrarse</a>
                            </li>
                        <?php endif ?> 
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container mt-3">